### PR TITLE
remove unnecessary clutter in `dummyOpeningFunction`

### PR DESCRIPTION
**Pull request by LFSaw**
not a lot of testing happened on this one (yet); please check/test if correct.

### CODE REVIEW

**Comment by LFSaw** [comment]
PR to wrong repo. @telephon, is there a flag that indicates the musikinformatik/steno as the new default PR target?

**Comment by telephon** [comment]
hm, I've never seen anything like that.

**Comment by LFSaw** [comment]
I rsearched a little... the default target for a forked repo is the one it was forked from. So, to change default PR target we'll need to delete our (personal github) repo and then fork a new one from musikInformatik. Alternatively, you, Julian, could 

1. delete the musikInformatik fork
2. transfer ownership of the telephon repo to musikinformatik
3. fork musikinformatik repo to telephon

this way, our issue discussions in the (now telephon) repo won't get lost. 


---
edit:
3. is now done, so I reopned this PR in musikinformatik

**Comment by LFSaw** [comment]
re-opened.

**Pull request merged**
