### PR TITLE
new replace all synths implementation (aka "!")

### PR DESCRIPTION
**Pull request by telephon**
This replaces the old "!" implementation by introducing it as an operator that can occupy any depth in the bracket stack.

E.g. 

`-- [(!fi)(fo)(f!a)]` will replace `fi` and `a` (in place).

Needs testing (!)

### CODE REVIEW

**Comment by rkuivila** [comment]
VarDiff takes a different approach to updating synthList and argList. It grabs the current synthList,
frees whatever is to be deleted, builds the new synthList and argList and then stashes them back in Steno.  This appears to me to be more flexible then the current approach which creates new synths whenever their ordinal positions in the synthList change.

**Comment by rkuivila** [comment]
Erm, previous comment was unclear:
The current approach **recreates existing** synths whenever their ordinal positions in the synthList change.

**Comment by telephon** [comment]
if I have a transition from `abc` to `[(abc)f xyz]`, will this keep `abc` untouched?

**Comment by rkuivila** [comment]
Hi Julian,

yes.
At the moment, VarDiff prints out:
newstring
removed synths  	(oldstring with underscores as placeholders for synths being reused)
newsynthstate 	(newstring with preexisting synths capitalized)

So the default diff starting at "faa" would look like:
"aaf"
f__
AAf

"faa"
__f
fAA

"aaf"
f__
AAf

But diff2 holds onto everything it can, so it would look like:

"aaf"
___
AAF

"faa"
___
FAA

"afa"
___
AFA


And the sequence you asked using diff0 for looks like:
"abc"
[((___)f)(xyz)]
ABC

"[((abc)f)(xyz)]"
___
[((ABC)f)(xyz)]

RJK

**Comment by LFSaw** [comment]
why are we discussing this now in this thread? took me a while to find it... should go to #26

**Comment by telephon** [comment]
yes, we shouln't. Has not much to do with it.

**Comment by telephon** [comment]
this has been merged through another PR already.

**Pull request closed without merging**
